# Generated by Django 5.0.4 on 2024-05-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car', models.CharField(max_length=50)),
                ('color_car', models.CharField(max_length=50)),
                ('relise_data', models.DateField(null=True)),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_car', models.TextField(blank=True)),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.typecar')),
            ],
        ),
    ]
