# Generated by Django 5.0.4 on 2024-05-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='prise',
            new_name='price',
        ),
    ]
